#!/usr/bin/env bash
#
# Refresh the workshop .env from an EXISTING Foundry resource group.
#
# Use this when your project is already provisioned (for example, a Skillable
# lab) and you just need a local .env. provision.sh also calls this at the end.
#
# Run:
#   ./setenv.sh                 # prompts for the resource group
#   ./setenv.sh <resource-group>
#   AZURE_RESOURCE_GROUP=my-rg ./setenv.sh
#
# It discovers your Foundry resource, project, region, and (if present) the
# connected Application Insights, then writes ../src/.env for every lab.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../src/.env"

command -v az >/dev/null || { echo "Azure CLI (az) is required."; exit 1; }

# --- Make sure we're signed in. ---
if ! az account show >/dev/null 2>&1; then
  echo "You're not signed in to Azure. Launching 'az login'..."
  az login >/dev/null
fi
if [[ -n "${AZURE_SUBSCRIPTION_ID:-}" ]]; then
  az account set --subscription "$AZURE_SUBSCRIPTION_ID"
fi
SUBSCRIPTION_ID="$(az account show --query id -o tsv)"

# --- Resolve the resource group (arg > env > prompt). ---
RESOURCE_GROUP="${1:-${AZURE_RESOURCE_GROUP:-}}"
if [[ -z "$RESOURCE_GROUP" ]]; then
  read -r -p "Resource group name: " RESOURCE_GROUP
fi
[[ -n "$RESOURCE_GROUP" ]] || { echo "A resource group is required."; exit 1; }

# --- Discover the Foundry resource + project. ---
ACCOUNT_NAME="${AZURE_AI_ACCOUNT_NAME:-$(az cognitiveservices account list \
  --resource-group "$RESOURCE_GROUP" \
  --query "[?kind=='AIServices'].name | [0]" -o tsv)}"
[[ -n "$ACCOUNT_NAME" ]] || { echo "No AI Services (Foundry) resource found in '$RESOURCE_GROUP'."; exit 1; }

PROJECT_NAME="${AZURE_AI_PROJECT_NAME:-$(az cognitiveservices account project list \
  --name "$ACCOUNT_NAME" --resource-group "$RESOURCE_GROUP" \
  --query "[0].name" -o tsv 2>/dev/null || true)}"
# The list returns the compound "account/project" name; keep only the leaf.
PROJECT_NAME="${PROJECT_NAME##*/}"
[[ -n "$PROJECT_NAME" ]] || { echo "No project found under account '$ACCOUNT_NAME'."; exit 1; }

LOCATION="$(az cognitiveservices account show --name "$ACCOUNT_NAME" \
  --resource-group "$RESOURCE_GROUP" --query location -o tsv)"

# Prefer the endpoint the service reports; fall back to the standard form.
PROJECT_ENDPOINT="$(az cognitiveservices account project show \
  --name "$ACCOUNT_NAME" --resource-group "$RESOURCE_GROUP" \
  --project-name "$PROJECT_NAME" \
  --query 'properties.endpoints."AI Foundry API"' -o tsv 2>/dev/null || true)"
[[ -n "$PROJECT_ENDPOINT" ]] || \
  PROJECT_ENDPOINT="https://${ACCOUNT_NAME}.services.ai.azure.com/api/projects/${PROJECT_NAME}"

# --- Find the connected Application Insights (for tracing), if any. ---
APPINSIGHTS_NAME="$(az resource list --resource-group "$RESOURCE_GROUP" \
  --resource-type "Microsoft.Insights/components" --query "[0].name" -o tsv 2>/dev/null || true)"
APPINSIGHTS_CONNECTION_STRING=""
if [[ -n "$APPINSIGHTS_NAME" ]]; then
  APPINSIGHTS_CONNECTION_STRING="$(az monitor app-insights component show \
    --app "$APPINSIGHTS_NAME" --resource-group "$RESOURCE_GROUP" \
    --query connectionString -o tsv 2>/dev/null || true)"
fi

# --- Write the single .env used by every lab. ---
mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setenv.sh — used by every TrailMate lab. Do not commit.
FOUNDRY_PROJECT_ENDPOINT=$PROJECT_ENDPOINT
TRAILMATE_MODEL_DEPLOYMENT=${TRAILMATE_MODEL_DEPLOYMENT:-gpt-5.4}
TRAILMATE_AGENT_NAME=${TRAILMATE_AGENT_NAME:-trailmate}
APPLICATIONINSIGHTS_CONNECTION_STRING=$APPINSIGHTS_CONNECTION_STRING
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
AZURE_RESOURCE_GROUP=$RESOURCE_GROUP
AZURE_AI_ACCOUNT_NAME=$ACCOUNT_NAME
AZURE_AI_PROJECT_NAME=$PROJECT_NAME
AZURE_LOCATION=$LOCATION
EOF

echo "Wrote $ENV_FILE"
echo "  Project endpoint : $PROJECT_ENDPOINT"
if [[ -n "$APPINSIGHTS_CONNECTION_STRING" ]]; then
  echo "  App Insights     : $APPINSIGHTS_NAME (tracing connection string set)"
else
  echo "  App Insights     : none found in $RESOURCE_GROUP (tracing not configured)"
fi
